### ISSUE TITLE
Received DEPTH_ZERO_SELF_SIGNED_CERT error

### ISSUE THREAD

**Issue by yoedy108** [IonicaBizau/youtube-api#50] opened 2016-01-17 10:54 UTC
@IonicaBizau Hi!
I saw your example and used it, thank you very much for creating this nodeJS module!
I followed your instructions and after I approve the app in the browser and get the code, I get this error: [Error: DEPTH_ZERO_SELF_SIGNED_CERT].
Can you help me debug this to understand what happened?

Thanks!

**Comment by IonicaBizau** [comment] 2016-01-17 11:00
Hmm... Can you run the process using `NODE_DEBUG=request node your-script.js` and post the output here?

The error looks to appear because of the https certificates... :thought_balloon:

**Comment by yoedy108** [comment] 2016-01-17 11:08
Here it is (and please excuse me for dropping the secret info: :bowtie:
```
Trying to get the token using the following code: 4/iF3BAopoV6dV-D13bdE1OuGQs0jkQmBavWoBJy2yeyM
REQUEST { method: 'POST',
  uri: 'https://accounts.google.com/o/oauth2/token',
  form:
   { code: '4/iF3BAopoV6dV-D13bdE1OuGQs0jkQmBavWoBJy2yeyM',
     client_id: 'xxxxx',
     client_secret: 'xxxxx',
     redirect_uri: 'http://localhost:5000/oauth2callback',
     grant_type: 'authorization_code' },
  json: true,
  headers: { 'User-Agent': 'google-api-nodejs-client/0.9.7' },
  callback: [Function] }
REQUEST make request https://accounts.google.com/o/oauth2/token
[Error: DEPTH_ZERO_SELF_SIGNED_CERT]
```

**Comment by IonicaBizau** [comment] 2016-01-17 11:38
That secret info is probably not that important. You're safe as long you keep the token secret.

Do you have some kind of firewall or anything related that would block that request?

Just in case, you can bypass this error by disabling the `NODE_TLS_REJECT_UNAUTHORIZED`:

```sh
NODE_TLS_REJECT_UNAUTHORIZED=0 node your-script.js
```

http://stackoverflow.com/q/10888610/1420197

**Comment by yoedy108** [comment] 2016-01-17 12:02
That indeed bypassed the error, but now I get another one:
__[Error: Parse Error] bytesParsed: 1037, code: 'HPE_INVALID_CONSTANT'__
The following output follows the one I sent before:
```
REQUEST make request https://accounts.google.com/o/oauth2/token
REQUEST onRequestResponse https://accounts.google.com/o/oauth2/token 200 { 'content-type': 'text/html; charset="utf-8"',
  'content-length': '936',
  connection: 'Close' }
REQUEST finish init function https://accounts.google.com/o/oauth2/token
{ [Error: Parse Error] bytesParsed: 1037, code: 'HPE_INVALID_CONSTANT' }
REQUEST response end https://accounts.google.com/o/oauth2/token 200 { 'content-type': 'text/html; charset="utf-8"',
  'content-length': '936',
  connection: 'Close' }
REQUEST end event https://accounts.google.com/o/oauth2/token
REQUEST has body https://accounts.google.com/o/oauth2/token 936
REQUEST emitting complete https://accounts.google.com/o/oauth2/token
```

Am I missing something here? I'm behind a proxy, do you think that I should add proxy info when starting the lien server? Authentication seems to work because I do get the code, but wait, the authentication is through the browser which has its own proxy configuration... So WDYT?

Thank you for the support so far!

**Comment by IonicaBizau** [comment] 2016-01-17 12:06
>  I'm behind a proxy, do you think that I should add proxy info when starting the lien server?

What kind of proxy? Somewhere when doing the `https` request, it fails... No idea why... :cry:

**Comment by yoedy108** [comment] 2016-01-17 12:09
An http web proxy at work...
The redirect-uri you asked to configure is http://localhost:5000/oauth2callback right? could it be that using this http redirect but authenticating with https causes this error?

**Comment by IonicaBizau** [comment] 2016-01-17 13:19
> An http web proxy at work...

Hmm... That could be the problem. Make sure that your proxy works fine with https...

**Comment by yoedy108** [comment] 2016-01-17 13:32
Actually connecting and modifying YouTube works just fine with my python script because there I can just configure httplib2 to use proxy so all YouTube API requests are sent through it.
I'm trying to rewrite the script in JS using your module and I'm not familiar with how to configure proxy for YouTube API in JS... 
I understand it's not related to lien or your module, but it would be great if you know how to add proxy configuration to YouTube API through your module.

**Comment by IonicaBizau** [comment] 2016-01-17 13:37
Ah, got it. This module uses the `googleapis` package and you can do: 

```js
var Youtube = require("youtube-api")
   , Google = require('googleapis')
   ;

Google.options({ proxy: "http://proxy.example.com" });
```

https://github.com/google/google-api-nodejs-client#example-specifying-a-default-proxy-and-auth-to-be-used-for-each-request

**Comment by yoedy108** [comment] 2016-01-17 14:00
Well... I added this proxy configuration to your index.js so it would be configured by default:
`Google.options({ proxy: "http://corporate_proxy:8000", auth: authObj });`
But unfortunately I still get the same Parse Error - HPE_INVALID_CONSTANT... :sob: 
Lien handles the requests and responses right? so maybe proxy configuration is required there as well? Is that even possible? :thought_balloon: 
Also, is there a way to output the responses so I can debug it? just like you showed me how to output the requests?

I really appreciate your time and help on this matter... :pray:

**Comment by IonicaBizau** [comment] 2016-01-17 14:25
Try to set up a basic script without `lien`. But I don't think the problem is `lien`. The requests are made by `googleapis` (and particularly by the `request` module).

Check if the problem still persists.

**Comment by yoedy108** [comment] 2016-01-19 11:56
I researched quite deeply and I think I got it... the problem is that Lien expects to receive 'contentType=html' but Google redirects the token info with json, so I get the HPE_INVALID_CONSTANT (Html Parse Error).
How can I specify in Lien that the content type should be json and not html?

**Comment by IonicaBizau** [comment] 2016-01-19 12:05
@yoedy108 Hmm... Are you talking about [this part](https://github.com/LienJS/Lien/blob/4203af8cd5f3dd4118649da63c74bd208143b81d/lib/index.js#L199-L215)? Where does lien expect `contentType:html`?

Interesting! :+1:

**Comment by yoedy108** [comment] 2016-01-19 12:49
Looks like it's the right place...
My problem is that I'm only a beginner on JS, and I'm not familiar with how to debug it, how to output the responses, or the form data received from Google into the redirect URL in Lien.
That's why I wanted to use your module, to spare me the tests on Google API JS examples...

Is there a way to force Lien to console output the form? responses? or expect other content type than html?

Thanks!

**Comment by IonicaBizau** [comment] 2016-01-19 12:55
> Is there a way to force Lien to console output the form?

You can edit the lien files from `node_modules` directory. Not sure, but the issue could be deeper in the `statique` package ([relevant snippets](https://github.com/IonicaBizau/node-statique/blob/27010ea1403adddb31c01c1eefd247bdb9816721/lib/index.js#L515-L525)).

**Comment by IonicaBizau** [comment] 2016-05-11 09:20
This should be fixed after upgrading to [`lien@1.x.x`](https://github.com/lienjs/lien), in #56. :tada:

**Closed by IonicaBizau** 2016-05-11 09:20 UTC
Labels: question

**Comment by yoedy108** [comment] 2016-05-17 08:08
Great! Thanks for getting this fixed!
I'll update the module and check...
